# Rebuilds the <!-- Pricing --> section of index.html and the matching Arabic keys in js/i18n.js
# from tools/pricing_data.py. Run: python3 tools/build_pricing.py
import os, re, sys, json
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.join(HERE, '..')
sys.path.insert(0, HERE)
from pricing_data import SEGMENTS, DH

ar = {
  'h.pr.eyebrow': 'الأسعار · الإمارات',
  'h.pr.title': 'كل شيء مشمول. بالدرهم. بلا مفاجآت.',
  'h.pr.lead': 'تُرخَّص البرمجيات لكل متجر شهرياً، وتُدفع سنوياً. وتُسعَّر المدفوعات حسب شبكة البطاقات وحجم المعاملات. دون إعادة تكامل عند الترقية.',
  'h.pr.popular': 'الأكثر طلباً',
  'h.pr.per': '/متجر/شهرياً',
  'h.pr.custom': 'مخصّص',
  'h.pr.note': 'ترخيص البرمجيات لكل متجر شهرياً · يُدفع سنوياً · الأسعار لا تشمل ضريبة القيمة المضافة · الأجهزة بدفعة واحدة',
  'h.pr.seg': 'نوع النشاط',
}
out = []
out.append('''    <!-- Pricing -->
    <section class="section" id="pricing" style="padding-top:0">
      <div class="container">
        <div class="section-head reveal">
          <span class="eyebrow" data-i18n="h.pr.eyebrow">Pricing · UAE</span>
          <h2 class="h2" data-i18n="h.pr.title">All in. In AED. No surprises.</h2>
          <p class="lead" data-i18n="h.pr.lead">Software is licensed per store, per month, billed annually. Payments are quoted per scheme &amp; volume. No re-integration when you move up.</p>
        </div>
        <div class="seg-toggle reveal" role="tablist" aria-label="Business type">
          <span class="pill" aria-hidden="true"></span>''')
for i, seg in enumerate(SEGMENTS):
    k = 'h.pr.seg.' + seg['id']; ar[k] = seg['ar']
    out.append(f'          <button type="button" role="tab" id="tab-{seg["id"]}" aria-controls="plans-{seg["id"]}" aria-selected="{"true" if i == 0 else "false"}" data-seg="{seg["id"]}" data-i18n="{k}">{seg["en"]}</button>')
out.append('        </div>')
for i, seg in enumerate(SEGMENTS):
    out.append(f'        <div class="price-grid plans" id="plans-{seg["id"]}" role="tabpanel" aria-labelledby="tab-{seg["id"]}"{"" if i == 0 else " hidden"}>')
    for j, p in enumerate(seg['plans']):
        b = f'h.pr.{seg["id"]}.{p["key"]}'
        ar[b + '.n'] = p['name'][1]; ar[b + '.p'] = p['who'][1]; ar[b + '.m'] = p['meta'][1]; ar[b + '.f0'] = p['head'][1]
        pop = p.get('popular')
        cls = 'price-card pop' if pop else 'price-card'
        delay = f' style="--d:{j * 0.1:.1f}s"' if j else ''
        out.append(f'          <article class="{cls} reveal"{delay}>')
        if pop: out.append('            <span class="badge" data-i18n="h.pr.popular">Most popular</span>')
        out.append(f'            <span class="tag" data-i18n="{b}.n">{p["name"][0]}</span>')
        out.append(f'            <p data-i18n="{b}.p">{p["who"][0]}</p>')
        if p['price'] is None:
            out.append('            <div class="price upper" data-i18n="h.pr.custom">Custom</div>')
        else:
            out.append(f'            <div class="price">{DH}{p["price"]} <small data-i18n="h.pr.per">/store/mo</small></div>')
        out.append(f'            <p class="price-meta" data-i18n="{b}.m">{p["meta"][0]}</p>')
        out.append('            <ul class="feat">')
        out.append(f'              <li data-i18n="{b}.f0">{p["head"][0]}</li>')
        for n, (en, a) in enumerate(p['feats'], 1):
            ar[f'{b}.f{n}'] = a
            out.append(f'              <li data-i18n="{b}.f{n}">{en}</li>')
        out.append('            </ul>')
        if p['price'] is None:
            out.append('            <a class="btn btn-primary" href="enterprise.html#contact" data-i18n="c.contactent">Contact enterprise</a>')
        else:
            out.append(f'            <button class="btn {"btn-white" if pop else "btn-primary"}" data-demo data-i18n="c.bookdemo">Book a demo</button>')
        out.append('          </article>')
    out.append('        </div>')
out.append('''        <p class="footnote reveal" data-i18n="h.pr.note">Software licensed per store, per month · billed annually · prices excl. VAT · hardware one-time</p>
      </div>
    </section>

''')
html = '\n'.join(out)

p = os.path.join(ROOT, 'index.html'); s = open(p).read()
a = s.index('    <!-- Pricing -->'); z = s.index('    <!-- Add-ons -->')
s = s[:a] + html + s[z:]
open(p, 'w').write(s)

# Arabic keys: drop old pricing keys, insert the generated block
p = os.path.join(ROOT, 'js/i18n.js'); s = open(p).read()
s = re.sub(r"\n    'h\.pr\.[^']*': '[^\n]*',", '', s)
block = ''.join(f"\n    {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}," for k, v in ar.items())
s = s.replace("    /* Add-ons */", "    /* Pricing (generated by tools/build_pricing.py) */" + block + "\n\n    /* Add-ons */", 1)
open(p, 'w').write(s)
print('ok', len(ar), 'arabic keys')
