# Software plans per segment, from the "youcloud flyer 01" retail and F&B flyers.
# Each item: (english, arabic). Used by tools/build_pricing.py.
DH = '<span class="dh" role="img" aria-label="AED"></span>'

SEGMENTS = [
  dict(id='retail', en='Retail', ar='التجزئة', plans=[
    dict(key='std', name=('Standard', 'القياسية'), price=19,
      who=('For a single shop that wants POS, stock, loyalty and VAT in one place.', 'لمتجر واحد يريد نقاط البيع والمخزون والولاء وضريبة القيمة المضافة في مكان واحد.'),
      meta=('POS, stock, loyalty, VAT · 1 user', 'نقاط البيع والمخزون والولاء وضريبة القيمة المضافة · مستخدم واحد'),
      head=('Core retail platform', 'منصة التجزئة الأساسية'),
      feats=[
        ('Checkout, multi-tender &amp; receipts', 'الدفع بوسائل متعددة والإيصالات'),
        ('Barcode scan, quick keys &amp; offline billing', 'مسح الباركود والمفاتيح السريعة والفوترة دون اتصال'),
        ('Catalog, batches, expiry &amp; serial numbers', 'الكتالوج والدفعات وتواريخ الانتهاء والأرقام التسلسلية'),
        ('Supplier management &amp; auto-reorder', 'إدارة المورّدين وإعادة الطلب التلقائي'),
        ('Cash, wallet, QR &amp; cards · T+2 settlement', 'نقد ومحافظ وQR وبطاقات · تسوية T+2'),
        ('Customer database (500) · points &amp; rewards', 'قاعدة عملاء (500) · نقاط ومكافآت'),
        ('1 marketplace connector', 'ربط مع منصة بيع إلكترونية واحدة'),
        ('Attendance &amp; shift scheduling', 'الحضور وجدولة الورديات'),
        ('Auto sales entries, VAT reports &amp; AI OCR', 'قيود مبيعات تلقائية وتقارير ضريبية وOCR بالذكاء الاصطناعي'),
      ]),
    dict(key='pow', name=('Power', 'المتقدمة'), price=49, popular=True,
      who=('For growing and multi-store retailers running HR, books and online sales.', 'لتجار التجزئة النامين ومتعددي الفروع الذين يديرون الموارد البشرية والدفاتر والبيع الإلكتروني.'),
      meta=('3 users · HR, books, WebShop', '3 مستخدمين · موارد بشرية ومحاسبة ومتجر إلكتروني'),
      head=('Everything in Standard, plus', 'كل ما في القياسية، بالإضافة إلى'),
      feats=[
        ('Bulk import / export &amp; inter-store transfers', 'استيراد وتصدير بالجملة وتحويل بين الفروع'),
        ('Shrinkage &amp; approved stock counts', 'إدارة الفاقد وجرد المخزون المعتمد'),
        ('Supplier &amp; vendor ledger', 'دفتر حسابات المورّدين'),
        ('Gift cards &amp; store credit', 'بطاقات الهدايا ورصيد المتجر'),
        ('Unlimited customers, full CRM &amp; VIP tiers', 'عملاء بلا حدود وإدارة كاملة للعملاء ومستويات VIP'),
        ('WebShop, social catalog &amp; unified stock', 'متجر إلكتروني وكتالوج اجتماعي ومخزون موحّد'),
        ('Full payroll &amp; WPS filing', 'رواتب كاملة وتقديم نظام حماية الأجور'),
        ('Bank reconciliation, P&amp;L &amp; balance sheet', 'مطابقة بنكية وقائمة أرباح وخسائر وميزانية عمومية'),
        ('Margin by SKU &amp; cross-store benchmarking', 'الهامش لكل صنف والمقارنة بين الفروع'),
      ]),
    dict(key='ent', name=('Enterprise', 'المؤسسات'), price=None,
      who=('For chains, franchises and multi-brand groups.', 'للسلاسل والامتيازات التجارية والمجموعات متعددة العلامات.'),
      meta=('Chains · franchise · SSO · 24/7 SLA', 'سلاسل · امتياز تجاري · تسجيل دخول موحّد · دعم على مدار الساعة'),
      head=('Everything in Power, plus', 'كل ما في المتقدمة، بالإضافة إلى'),
      feats=[
        ('3PL logistics integrations', 'تكامل مع مزوّدي الخدمات اللوجستية (3PL)'),
        ('White-label own storefront', 'متجر إلكتروني بعلامتك التجارية'),
        ('Franchise / chain governance', 'حوكمة الامتيازات والسلاسل'),
        ('SSO (SAML / OIDC) + API keys', 'تسجيل دخول موحّد (SAML / OIDC) + مفاتيح API'),
        ('Dedicated field ops rollout', 'فريق ميداني مخصّص للإطلاق'),
        ('24/7 phone support · 1-hr SLA · named CSM', 'دعم هاتفي على مدار الساعة · استجابة خلال ساعة · مدير نجاح مخصّص'),
      ]),
  ]),
  dict(id='fnb', en='F&amp;B / Restaurant', ar='المطاعم والمقاهي', plans=[
    dict(key='std', name=('Standard', 'القياسية'), price=39,
      who=('For a restaurant, café or cloud kitchen with one kitchen screen.', 'لمطعم أو مقهى أو مطبخ سحابي بشاشة مطبخ واحدة.'),
      meta=('1 user · full KDS · 3 aggregators · QR', 'مستخدم واحد · شاشة مطبخ كاملة · 3 تطبيقات توصيل · QR'),
      head=('Core restaurant platform', 'منصة المطاعم الأساسية'),
      feats=[
        ('Unlimited menu items, split bills &amp; receipts', 'أصناف قائمة بلا حدود وتقسيم الفواتير والإيصالات'),
        ('Offline ordering, floor plan &amp; reservations', 'الطلب دون اتصال ومخطط الصالة والحجوزات'),
        ('Full KDS with prep timers &amp; 86-sync', 'شاشة مطبخ كاملة مع مؤقتات التحضير وإيقاف الأصناف النافدة'),
        ('Ingredient stock &amp; low-stock alerts', 'مخزون المكوّنات وتنبيهات انخفاض المخزون'),
        ('3 aggregators + direct delivery app (0% commission)', '3 تطبيقات توصيل + تطبيق توصيل مباشر (بلا عمولة)'),
        ('Cash, wallet, cards &amp; pay-at-table · T+2 settlement', 'نقد ومحافظ وبطاقات والدفع على الطاولة · تسوية T+2'),
        ('Guest database (500), points &amp; QR order-and-pay', 'قاعدة ضيوف (500) ونقاط والطلب والدفع عبر QR'),
        ('Attendance &amp; shift scheduling', 'الحضور وجدولة الورديات'),
        ('Auto sales entries, VAT reports &amp; aggregator recon', 'قيود مبيعات تلقائية وتقارير ضريبية ومطابقة تطبيقات التوصيل'),
      ]),
    dict(key='pow', name=('Power', 'المتقدمة'), price=99, popular=True,
      who=('For busy and multi-outlet restaurants running every channel, HR and books.', 'للمطاعم المزدحمة ومتعددة الفروع التي تدير كل القنوات والموارد البشرية والدفاتر.'),
      meta=('2 users · all aggregators · HR &amp; books', 'مستخدمان · كل تطبيقات التوصيل · موارد بشرية ومحاسبة'),
      head=('Everything in Standard, plus', 'كل ما في القياسية، بالإضافة إلى'),
      feats=[
        ('Courses &amp; allergen rules', 'تسلسل الأطباق وقواعد مسبّبات الحساسية'),
        ('2 KDS stations, course firing &amp; expo view', 'محطتا مطبخ وتسلسل التقديم وشاشة التجهيز'),
        ('Recipe costing per dish &amp; supplier management', 'تكلفة الوصفة لكل طبق وإدارة المورّدين'),
        ('All aggregators in one KDS + commission reports', 'كل تطبيقات التوصيل في شاشة واحدة + تقارير العمولات'),
        ('Social ordering — FB, IG, WhatsApp', 'الطلب عبر فيسبوك وإنستغرام وواتساب'),
        ('Gift cards, unlimited guests &amp; full CRM', 'بطاقات الهدايا وضيوف بلا حدود وإدارة كاملة للعملاء'),
        ('Full payroll, WPS &amp; tip pooling', 'رواتب كاملة ونظام حماية الأجور وتجميع الإكراميات'),
        ('Bank recon, P&amp;L &amp; balance sheet', 'مطابقة بنكية وقائمة أرباح وخسائر وميزانية عمومية'),
        ('Margin by dish &amp; anomaly alerts', 'الهامش لكل طبق وتنبيهات الحالات غير المعتادة'),
      ]),
    dict(key='ent', name=('Enterprise', 'المؤسسات'), price=None,
      who=('For restaurant chains, franchises and multi-brand groups.', 'لسلاسل المطاعم والامتيازات التجارية والمجموعات متعددة العلامات.'),
      meta=('Chains · franchise · SSO · 24/7 SLA', 'سلاسل · امتياز تجاري · تسجيل دخول موحّد · دعم على مدار الساعة'),
      head=('Everything in Power, plus', 'كل ما في المتقدمة، بالإضافة إلى'),
      feats=[
        ('Menu engineering', 'هندسة القوائم'),
        ('Central kitchen &amp; commissary', 'المطبخ المركزي والإمداد'),
        ('Franchise / chain governance', 'حوكمة الامتيازات والسلاسل'),
        ('SSO (SAML / OIDC) + API keys', 'تسجيل دخول موحّد (SAML / OIDC) + مفاتيح API'),
        ('Dedicated field ops rollout', 'فريق ميداني مخصّص للإطلاق'),
        ('24/7 phone support · 1-hr SLA · named CSM', 'دعم هاتفي على مدار الساعة · استجابة خلال ساعة · مدير نجاح مخصّص'),
      ]),
  ]),
]
